title: Herbawi's Blog
description: Al-Herbawi's technical blog and profile
remote_theme: just-the-docs/just-the-docs

# Enable the sidebar table of contents navigation
nav_enabled: true
enable_heading_anchors: true
